# Generated by Django 2.2.3 on 2019-08-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abhi3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_registrations',
            old_name='Name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=225)),
                ('e_salary', models.CharField(max_length=225)),
                ('e_exp', models.CharField(max_length=225)),
                ('e_profile', models.CharField(max_length=225)),
                ('e_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abhi3.tb_registrations')),
            ],
        ),
    ]
