# Generated by Django 2.2.3 on 2019-10-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191001_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name1',
            new_name='name',
        ),
    ]
